# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97155be3d480e2ee1a8877f3ec0683528ba5e8d339de4366b545d036708d0d26dd17636029577b85a0de068b25c2233f56646fb5ebe4c7e06c12d8feac9b4bd6

test:
  secret_key_base: e378acb16b2a2e44a6be7e19e26e30790df0327a6ea1cb0635067eeb4e0ce5cc9778a6a9196233e10fdae87b1bff2acbda142c4212021100a256125ada061983

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
